# Generated by Django 3.2 on 2021-11-03 09:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210812_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(default='123'),
            preserve_default=False,
        ),
    ]
